# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git tmux)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Because Bat is awesome, but I keep forgetting :|
alias cat='bat'

# Git Tweaks
# In Zsh, arguments are automatically appended, so no need for $argv
alias green='git checkout green'
alias master='git checkout master'
alias main='git checkout main'
alias push='git push'
alias branches='git branch -vv | rg -v "\*" | awk "{print \$1}"'

# sudo wrappers
alias please='sudo'
alias pls='sudo'

# Recommended replacement reminders
# We use 'echo' here to keep the reminder from executing the original command
alias find='echo "Use fd"'
alias cal='echo "Use ccal"'

# Docker Tweaks
alias dr='docker run'
alias drit='docker run --rm -ti'
alias deit='docker exec -ti'

# Other utilities
alias filedate='date +"%d%m%y_%H%m"'

# Flexible Tmux Function: Use argument or default to 'default-session'

# Robust Tmux Function: Attach if exists, otherwise create.
tm() {
    local sessionname="default-session"

    # Use argument if provided, otherwise use the default name
    if [ -n "$1" ]; then
        sessionname="$1"
    fi

    # Attempt to attach to the session (without -A)
    command tmux attach-session -t "$sessionname" 2>/dev/null

    # $? holds the exit code of the last command (0 means success)
    # If the attach failed (session does not exist), $? will be non-zero.
    if [ $? -ne 0 ]; then
        # Create a new session with the target name
        echo "Creating new tmux session: $sessionname"
        command tmux new-session -s "$sessionname"
    fi
}

# --- Custom Prompt Logic ---

# Function to generate the entire first line of the prompt
# Note: In Zsh, the return value of a function can be used in the PROMPT.
_custom_prompt_line() {
    # 1. Start with the directory path (shorthand and full)
    # %F{...} sets the color
    local first_line="%F{green}%~%f"
    
    # 2. Check if we are in a Git repository and append the status
    if git rev-parse --is-inside-work-tree &>/dev/null; then
        # Call your fast gitstatus tool and append its output
        # We wrap it in a custom color (e.g., green)
        local git_output=$(gitstatus)
        if [ -n "$git_output" ]; then
            first_line="$first_line %F{cyan}$git_output%f"
        fi
    fi

    # Print the resulting first line
    echo "$first_line"
}

# --- PROMPT Definition ---

# Set the PROMPT variable to call the function and add the separator line
# The `$(...)` executes the function, and $'\n' forces the newline.
PROMPT='$(_custom_prompt_line)
; '
